### ISSUE TITLE
chainmap missing from requirements.txt

### ISSUE THREAD

**Issue by JnyJny** [jjangsangy/Word2Seq#1]
After installing charrnn via pip, the following error was emitted:

    $ charrnn -h
     Traceback (most recent call last):
      File "/usr/local/bin/charrnn", line 7, in <module>
        from charrnn.__main__ import main
      File "/usr/local/lib/python3.6/site-packages/charrnn/__init__.py", line 24, in <module>
        from . train import *
      File "/usr/local/lib/python3.6/site-packages/charrnn/train.py", line 14, in <module>
        from chainmap import ChainMap
     ModuleNotFoundError: No module named 'chainmap'

After installing chainmap via pip, the charrnn invocation emits the expected help message.

**Comment by jjangsangy** [comment]
Just took care of it, thanks for the catch!
